<?php /** @var \App\Views\Layouts\layout $this */ ?><!DOCTYPE HTML>
<html lang="en-US">
	<head>
		<meta charset="UTF-8" />
		<title><?=$title?> | MvcCore Ag Grid Demo</title>
		<base href="<?=$basePath?>" />
		<link rel="shortcut icon" href="<?=$assetUrl('/static/img/favicon.ico')?>" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=2.0, user-scalable=yes" />
		<meta name="mobile-web-app-capable" content="yes" />
		<script>var timestamp=+new Date;(function(a,b,c,d,e,f){if(b[c]('Opera'))b=b[d](e,f);if(b[c]('Trident/'))b=b[d](/ rv:([0-9\.]*)\)/g,e+'$1)');a.setAttribute('data-browser',b);a.className=f;})(document.documentElement,navigator.userAgent,'match','replace',' MSIE ','')</script>
		<?=$this->Css('fixedHead')?>
		<?=$this->Css('varHead')?>
		<?=$this->Css('agGrid')?>
		<?=$this->Js('agGrid')?>
		<?/*=$this->Js('fixedHead')->Render()*/?>
		<meta name="author" content="Tom Flidr <tomflidr(at)gmail(dot)com>" />
	</head>
	<body>
		<div class="master-container route-<?=$currentRouteCssClass?>">

			<header>MvcCore Example - AgGrid</header>

			<nav>
				<ol>
					<li><a href="<?=$this->Url('Index:')?>">Demos</a></li>
					<li><a href="<?=$this->Url('Client:')?>">Clients</a></li>
					<li><a href="<?=$this->Url('Dealer:')?>">Dealers</a></li>
					<li><a href="<?=$this->Url('Order:')?>">Orders</a></li>
				</ol>
			</nav>

			<main>
				<h1><?=$heading?></h1>
				<?=$this->GetContent()?>
			</main>

		</div>

		<?/*=$this->Js('varFoot')*/?>
	</body>
</html>
